# Generated by Django 3.2.20 on 2023-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
