# Generated by Django 3.2.20 on 2023-08-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20230803_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cloudinary_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
