# Generated by Django 3.2.20 on 2023-08-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
    ]
