# Generated by Django 3.2.20 on 2023-08-11 18:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_rename_bio_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='empty', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
