# Generated by Django 3.2.20 on 2023-08-15 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0010_profile_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thread',
        ),
    ]
