# Generated by Django 3.2.20 on 2023-08-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_rename_like_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='thread',
        ),
    ]
