# Generated by Django 3.2.20 on 2023-08-15 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_alter_reply_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='post',
            new_name='thread',
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('thread', 'user')},
        ),
    ]
