# Generated by Django 3.2.20 on 2023-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_upvote_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
