# Generated by Django 3.2.20 on 2023-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_thread_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
