# Generated by Django 3.2.20 on 2023-08-16 17:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_thread_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
