# Generated by Django 3.2.20 on 2023-08-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.channel'),
            preserve_default=False,
        ),
    ]
