# Generated by Django 3.2.20 on 2023-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_thread_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='DEFAULT'),
            preserve_default=False,
        ),
    ]
